version: '3'

services:
    # copy this file to your local videos folder
    # rename file to docker-compose.yml
    # open a command prompt on your OS
    # navigate to local videos folder
    # execute: docker-compose up -d
    # http://localhost:3060
    webserver:
        image: php:7-alpine
        container_name: twitch-chatbot-videos-folder
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t ./
        environment:
            docker: "true"
        ports:
            - 3060:80
        volumes:
            - .:/var/www
