# ----- Unix -------- #
# docker run --rm --interactive --tty --volume $PWD:/app composer create-project --ignore-platform-reqs --no-dev codelinered/twitch-chatbot twitch-chatbot "dev-production"
# cd twitch-chatbot
# docker run --rm --interactive --tty --volume $PWD:/app composer update --no-dev
# ----- Windows ----- #
# docker run --rm --interactive --tty --volume %cd%:/app composer create-project --ignore-platform-reqs --no-dev codelinered/twitch-chatbot twitch-chatbot "dev-production"
# cd twitch-chatbot
# docker run --rm --interactive --tty --volume %cd%:/app composer update --no-dev

version: '3'

volumes:
    logs:
        driver: local

# docker-compose up -d
services:
    # http://localhost:3050
    # docker exec -ti twitch-chatbot php --version
    webserver:
        image: php:7-alpine
        container_name: twitch-chatbot
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t public
        environment:
            docker: "true"
        ports:
            - 3050:80
        volumes:
            - .:/var/www
            - logs:/var/www/logs
