version: '3'

volumes:
    logs:
        driver: local

# docker-compose up -d
services:
    # http://localhost:3050
    # docker exec -ti twitch-chatbot php --version
    webserver:
        image: php:7-alpine
        container_name: twitch-chatbot
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 3050:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    # docker-compose run composer install --no-dev
    # docker-compose run composer require user/pack
    composer:
        image: composer
        volumes:
            - .:/var/www
        working_dir: /var/www
